{% set version = "0.4.11" %}

package:
  name: peregrine-2021
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/cschin/peregrine-2021/archive/refs/tags/v{{version}}.tar.gz
  sha256: 5b260b10243e2d7cdc3f0b0c94020b50b034e378544146f453115703c5e3de6d

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust >=1.58.0
    - clangdev
    - pkg-config
    - make
    - cmake
  host:
    - gsl
    - libcblas
    - openssl
  run:
    - jq
    - exonerate
    - parallel
    - pigz
    - samtools
    - tzdata
    - wget

test:
  commands:
    - pg_asm --help

about:
  home: https://github.com/cschin/peregrine-2021
  license: CC BY-NC-SA 4.0
  license_family: CC
  license_file: LICENSE
  summary: A genome assembler designed for long-reads that have good enough accuracy
extra:
  recipe-maintainers:
    - rpetit3
